### ISSUE TITLE
Doesn't build with zita-convolver-4.0.0

### ISSUE THREAD

**Issue by yurivict** [tomszilagyi/ir.lv2#8]
The build fails:
```
c++ ir.cc  -Wall -I. -I/usr/include `pkg-config --cflags gtk+-2.0` `pkg-config --cflags gthread-2.0` -D__STDC_FORMAT_MACROS -O2 -ffast-math -D_HAVE_GTK_ATLEAST_2_20 -c -fPIC -o ir.o
ir.cc:40:2: error: "This version of IR requires zita-convolver 3.x.x"
#error "This version of IR requires zita-convolver 3.x.x"
 ^
ir.cc:526:9: error: no member named 'set_density' in 'Convproc'
                conv->set_density(1);
                ~~~~  ^
ir.cc:533:24: error: too few arguments to function call, expected 7, have 6
                                  Convproc::MAXPART);
                                                   ^
/usr/local/include/zita-convolver.h:387:5: note: 'configure' declared here
    int configure (uint32_t  ninp,
    ^
```

**Comment by tomszilagyi** [comment]
As the error message says.
Patch welcome.

**Comment by ccaudle** [comment]
Hermann Meyer ("brummer") just submitted pull requests to add support for the new zita-convolver version.

**Comment by tomszilagyi** [comment]
PRs merged. Thanks for driving the issue.
